# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 19:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'New Board', max_length=128)),
                ('n_users', models.IntegerField(default=0)),
                ('n_columns', models.IntegerField(default=0)),
                ('n_cards', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'New Card', max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('expire_date', models.DateField(default=datetime.datetime.now)),
                ('story_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'New Column', max_length=128)),
                ('n_cards', models.IntegerField(default=0)),
                ('mother_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progetto_isw.Board')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='mother_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progetto_isw.Column'),
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
