# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progetto_isw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='mother_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progetto_isw.Column'),
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='column',
            name='mother_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='progetto_isw.Board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default=b'New Board', max_length=128),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default=b'New Card', max_length=128),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(default=b'New Column', max_length=128),
        ),
    ]
